* Acceso a carpetas compartidas desde infraestructura local
#+begin_quote
[!IMPORTANT]
Utilizaremos la *Landing Zone* para realizar esta práctica.
#+end_quote

Los objetivos de esta práctica son los siguientes:
- Configurar una VPC con un sistema de archivos EFS
- Crear una conexión AWS Client VPN para acceso remoto a la VPC
- Montar sistemas de archivos desde clientes Linux desplegados en local (conectados mediante VPN) y máquinas EC2 desplegadas en la VPC
- Probar conectividad y funcionalidad del sistema de archivos

* Arquitectura de la solución
La práctica simula un escenario híbrido donde usuarios remotos acceden a sistemas de archivos compartidos en AWS:

#+BEGIN_SRC
[Cliente On-Premise] ---> [AWS Client VPN] ---> [VPC] ---> [EFS]
                                                  |
                                            [Instancias EC2]
#+END_SRC

* Recursos a implementar
** Infraestructura de Red
- VPC con subredes públicas y privadas
- Internet Gateway
- NAT Gateway
- Tablas de enrutamiento
- Grupos de seguridad

** Sistemas de Archivos
- Amazon EFS

** Conectividad VPN
- AWS Client VPN Endpoint
- Certificados de autenticación
- Configuración de rutas VPN

** Instancias de Prueba
- EC2 Linux (Amazon Linux 2023)
- Máquina virtual Linux o equipo local

* 1. Creación de la infraestructura de red
Crea la siguiente infraestructura:
- VPC, con *resolución y asignación de DNS*. CIDR ~172.16.0.0/16~
- Subred pública. CIDR ~172.16.1.0/24~
- Subred privada. CIDR ~172.16.2.0/24~
- Internet Gateway
- NAT Gateway

Puedes utilizar el asistente para ello.

A continuación, crea *3 grupos de seguridad*:
- ~SG-instancias~ - Debe permitir todo tráfico saliente
- ~SG-clienteVPN~ - Debe permitir todo tráfico saliente y el tráfico *entrante* al puerto *443* (HTTPS)
- ~SG-EFS~ - Debe permitir todo tráfico saliente y el tráfico *entrante* al puerto *2049* (NFS) únicamente *desde los grupos de seguridad* ~SG-instancias~ y ~SG-clienteVPN~

* 2. Sistema de archivos EFS
Crea un sistema de archivos EFS con un *punto de montaje* en la *subred privada* de la VPC creada anteriormente. Asocia el *grupo de seguridad* ~SG-EFS~ al punto de montaje.

* 3. Conectividad VPN
Crea un cliente VPN tal como has aprendido en el módulo de Redes. Para ello, deberás:
- *Generar certificados* de cliente y servidor. Para ello puedes utilizar https://github.com/OpenVPN/easy-rsa
  A continuación se indican los comandos necesarios para ello:
  #+BEGIN_SRC bash
    # Instalar easy-rsa
    git clone https://github.com/OpenVPN/easy-rsa.git
    cd easy-rsa/easyrsa3

    # Inicializar PKI
    ./easyrsa init-pki

    # Crear CA
    ./easyrsa build-ca nopass
  #+END_SRC
  #+BEGIN_SRC bash
    # Crear certificado del servidor
    ./easyrsa build-server-full servidor.practica.vpn nopass
  #+END_SRC
  #+BEGIN_SRC bash
    # Crear certificado del cliente
    ./easyrsa build-client-full cliente.practica.vpn nopass
  #+END_SRC
- *Importar* los certificados en *AWS Certificate Manager*. Puedes utilizar este código para hacerlo desde la CLI si has generado los certificados con el paso anterior:
  #+BEGIN_SRC bash
    # Importar certificado del servidor
    aws acm import-certificate \
        --certificate fileb://pki/issued/servidor.practica.vpn.crt \
        --private-key fileb://pki/private/servidor.practica.vpn.key \
        --certificate-chain fileb://pki/ca.crt
  #+END_SRC
  #+BEGIN_SRC bash
    # Importar certificado del cliente
    aws acm import-certificate \
        --certificate fileb://pki/issued/cliente.practica.vpn.crt \
        --private-key fileb://pki/private/cliente.practica.vpn.key \
        --certificate-chain fileb://pki/ca.crt
  #+END_SRC
- Crear un *Client VPN Endpoint*
  - Utiliza *autenticación mutua* indicando los *certificados de servidor y cliente*
  - CIDR - ~192.168.0.0/16~
  - DNS 1 - ~172.16.0.2~ (es la IP del servidor DNS de la VPC). También podemos utilizar la IP genérica ~169.254.169.253~, tal como indica la [[https://docs.aws.amazon.com/vpc/latest/userguide/AmazonDNS-concepts.html#AmazonDNS][documentación]].
  - Asociar el *grupo de seguridad* ~SG-clienteVPN~ a la conexión creada
- Asociar el cliente a la *subred privada* de la VPC creada anteriormente.
- Crear una *regla de autorización* que permita el acceso al rango de IPs de la VPC: ~172.16.0.0/16~

* 4. Conexión
** Instancia Linux en EC2
- Crea una instancia EC2 en la *subred privada* creada anteriormente.
- *Monta el sistema de ficheros* EFS en una carpeta. Recuerda que puedes consultar las instrucciones de montaje en el propio servicio EFS en la consola.
- *Crea un archivo* con tu *NOMBRE y APELLIDOS* en su interior.

** Equipo local
- Descarga la configuración VPN en una *máquina Linux local*. Puedes utilizar tu equipo o una máquina virtual local
- Conéctate a la VPN mediante el archivo de configuración
- *Monta* el sistema de ficheros EFS en una carpeta. Comprueba que *aparece el archivo* creado anteriormente desde la máquina EC2

** Entrega
Documenta la realización de la práctica explicando los pasos seguidos. Incluye las *capturas de pantalla* necesarias. Recuerda mostrar tus datos personales (nombre y apellidos, iniciales) en aquellos apartados donde se indique.

** Limpieza
Al finalizar, *elimina* la *máquina virtual*, el sistema de ficheros *EFS*, la *asociación de subred* del cliente VPN, el *cliente VPN*, la *NAT Gateway*, la *IP elástica* asociada a la NAT Gateway, la *VPC* con todos sus recursos y los *certificados*.
